### ISSUE TITLE
Release preparedness

### ISSUE THREAD

**Issue by teyc** [serilog-web/classic-webapi#1]
Creating a list of tasks associated with releasing this package
1. Appveyor builds
2. NuGet repository access
3. Figure out which precedent versions to declare in `packages.config`

For reference, it's currently

```
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net452" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="net452" />
  <package id="Serilog" version="1.5.7" targetFramework="net452" />
  <package id="SerilogWeb.Classic" version="2.0.6" targetFramework="net452" />
```

**Comment by nblumhardt** [comment]
I've made some progress - the project now matches up with the SerilogWeb.Classic structure a bit more closely (for better or for worse) and [builds through AppVeyor](https://ci.appveyor.com/project/serilog-web/classic-webapi). The [package is on NuGet](https://www.nuget.org/packages/serilogweb.classic.webapi).

:fireworks: 

Still remaining:
- Work out why the SerilogWeb projects can't be located on GitHub by AppVeyor (ended up having to use the fallback Git integration, which doesn't pick up commit messages properly, and polls for changes)
- Get you some permission to the build and feed

Have to sign off for tonight though :-)

**Comment by nblumhardt** [comment]
`net451` support probably should go onto that list, unless it causes us problems with WebAPI version compatibility.

**Comment by nblumhardt** [comment]
Hey guys - I've changed the target framework to 4.5+, should cover the only feedback we've had so far. To add you to AppVeyor I need the email addresses with which you sign in there (if you have an account). Drop me an email with this info and I'll set it up.

Otherwise, all good for now!
