### ISSUE TITLE
Unauthorized requests do not add data to HttpContext.Items

### ISSUE THREAD

**Issue by gareth-james** [serilog-web/classic-webapi#12]
If an Authorize filter attribute determines the request is unauthorized, it does not add the data for the enrichers to HttpContext.Items.

Perhaps we could have StoreWebApInfoInHttpContextAuthorizationFilter which does the same as the action filter and move the code which processes the HttpActionContext into a separate class for sharing?

Happy to submit a pull request if this is acceptable.

Thanks

**Comment by tsimbalar** [comment]
Hi,
yes I think that would make sense .... `ActionFilter`s code seem to happen later in the pipeline than `AuthorizationFilter`s. We'll be happy to take a PR :)

**Comment by gareth-james** [comment]
Thanks @tsimbalar, I'll get on it.

**Comment by tsimbalar** [comment]
Actually, we can probably just have one AuthorizationFilter and get rid of the ActionFilter , but I may be wrong :p

**Comment by gareth-james** [comment]
I think we would still need the action filter for requests that are not authorized, which is why I haven't automatically added the authorization filter to the global configuration. I can't think of a way of getting rid of one at the moment.
