### ISSUE TITLE
WebApi global ExceptionHandler always returns HTML instead of JSON when package SerilogWeb.Classic.WebApi is present in project

### ISSUE THREAD

**Issue by victorvogelpoel** [serilog-web/classic-webapi#16]
I have an global ExceptionHandler in my WebAPI. Any response from the ExceptionHandler is returned as HTML and not JSON, which is the default content encoding.

Upon removing the SerilogWeb.Classic.WebApi package from the project, responses are no longer in HTML, but now in JSON.

Stackoverflow https://stackoverflow.com/questions/47778018/exceptionhandler-being-called-but-not-returning-json describes the issue and also the culprit, which is SerilogWeb.Classic.WebApi.

**Comment by tsimbalar** [comment]
Hi Victor, 

thanks for sharing. 

It looks very similar to https://github.com/serilog-web/classic-webapi/issues/3 that said : 

> When I'm using own `ExceptionFilterAttribute` and _SerilogWeb.Classic.WebApi_ I get always back status code 500 and HTML as response when exception is thrown, ignoring the `Accept` header and defined status code as to be returned

Would love to be able to fix it.

Do you happen to have a minimal repro project that we could use to analyze and try to fix the issue ?

We also had a discussion going on there in [`SerilogWeb.Classic`](https://github.com/serilog-web/classic/issues/48) to improve the mechanism we use to report exceptions, if you can chime in ;)

Thanks

**Comment by victorvogelpoel** [comment]
It reads as something similar, yes.
And no sorry, I don't have a minimal project, just a client's project.

Have to whip up something...

**Comment by victorvogelpoel** [comment]
Minimal project added. The ZIP contains no packages due to issue file upload constraints; you'll have to do a package restore.

SerilogWeb.Classic.WebApi is referenced in this project. Requesting /values/5 will throw a IDNotFoundException, which is intercepted by the global exception handler. The handler returns an HTML page when SerilogWeb.Classic.WebApi is referenced.

Remove SerilogWeb.Classic.WebApi package from the project and comment out its methods in the code and web.config. Now request /values/5 again, and it will show the exception message in JSON.

Good hunting!

[WebAPISerilogClassicIssue2.zip](https://github.com/serilog-web/classic-webapi/files/2912364/WebAPISerilogClassicIssue2.zip)

**Comment by tsimbalar** [comment]
Thanks Victor, that's super useful ! 

I guess that's the push we needed to start implementing https://github.com/serilog-web/classic/issues/48 and have a less intrusive integration ;)

Will keep you posted !

**Comment by tsimbalar** [comment]
This should now be fixed as per [_SerilogWeb.Classic.WebApi_ **v4.0.5**](https://www.nuget.org/packages/SerilogWeb.Classic.WebApi/4.0.5) . It does at least fix it in your repro 🎉  !


I would love it if you could give it a try and confirm that it solves your issue !

**Comment by victorvogelpoel** [comment]
Thanks @tsimbalar. I'll check tomorrow morning.

**Comment by victorvogelpoel** [comment]
YES! issue is solved! Thanks a lot!

**Comment by tsimbalar** [comment]
Great  !  Glad that it fixed it, and sorry for the headaches it might have
caused you...
