### ISSUE TITLE
I have a problem when using own ExceptionFilterAttribute and SerilogWeb.Classic.WebApi

### ISSUE THREAD

**Issue by akalcik** [serilog-web/classic-webapi#3]
When I'm using own `ExceptionFilterAttribute` and _SerilogWeb.Classic.WebApi_ I get always back status code 500 and HTML as response when exception is thrown, ignoring the `Accept` header and defined status code as to be returned. See more description of issue on [http://stackoverflow.com/questions/37058052/raising-the-httpresponseexception-in-exceptionfilterattribute-with-custom-status](StackOverflow).

**Comment by IanYates** [comment]
There's very little code in this repository - see the two files at https://github.com/serilog-web/classic-webapi/tree/master/src/SerilogWeb.Classic.WebApi/Classic/WebApi

I suspect there's something going wrong with Serilog trying to handle the exception, which is then causing a separate exception to be thrown leading to your 500.

Could you try copying the two files from this repository into your own code and see if you get an exception from this code?  You could also try disabling "JustMyCode" to see if something can be spotted.

**Comment by akalcik** [comment]
I will definitely look into it.

**Comment by akalcik** [comment]
I thing I have a idea what is changing the expected behaviour. 
![Lifecycle of exception logging](https://cloud.githubusercontent.com/assets/7405311/15257481/d4e9ddb2-1946-11e6-9f75-f94582debc71.png)

The code to which I refer is [WebApiExceptionLogger.cs](https://github.com/serilog-web/classic-webapi/blob/ba030cf51f5a26be7f81ca820698d3a0b5097ff3/src/SerilogWeb.Classic.WebApi/Classic/WebApi/WebApiExceptionLogger.cs)

**Comment by akalcik** [comment]
This is workaround. Instead of using _SerilogWeb.Classic.WebApi_ i wrote my own _ExceptionLogger_ which is calling the Serilog with help of ([LibLob](https://github.com/damianh/LibLog)) directly.

```
namespace TestWebApi.Loggers
{
    public class WebApiExceptionLogger : ExceptionLogger
    {
        public override void Log(ExceptionLoggerContext context)
        {
            ILog _logger = LogProvider.GetCurrentClassLogger();
            _logger.ErrorException(context.Exception.Message, context.Exception);
        }
    }
}
```

**Comment by nblumhardt** [comment]
@akalcik thanks for posting the analysis! A great help, thanks.

@teyc any thoughts on how we can get around this issue/alternative impls?

Cheers!

**Comment by teyc** [comment]
Thanks Anton!

Nick, Ian, using ExceptionLogger seems to be the cleaner method. Since
multiple people have been affected by this issue, any problems with
switching implementations altogether?

**Comment by IanYates** [comment]
No complaints from me.  I had looked at this on the weekend and for some reason the point being made didn't 'click' immediately - serves me right for reading late on a Saturday night :)

**Comment by nblumhardt** [comment]
Sounds like a plan :+1:

**Comment by akalcik** [comment]
@IanYates @nblumhardt @teyc Thank you!

**Comment by tsimbalar** [comment]
Closing it for lack of activity. Happy to re-open later on .... I'm wondering if serilog-web/classic#48 might help, when using a less intrusive (than `Context.AddError()`) mechanism.

**Comment by cfguimaraes** [comment]
I have this problem now,
My `ExceptionFilterAttribute` always return HttpStatusCode == 500, after uninstall this package all seems correct.

**Comment by tsimbalar** [comment]
@cfguimaraes  Could you post more information about what the symptoms are, your configuration etc ? ideally in a separate issue :) 

Thanks a lot !
