### ISSUE TITLE
Broken AppVeyor build

### ISSUE THREAD

**Issue by tsimbalar** [serilog-web/classic-webapi#6]
Currenly the appveyor build is failing ...

See for instance https://ci.appveyor.com/project/serilog-web/classic-webapi/branch/master 

```
Classic\WebApi\Enrichers\BaseWebApiContextInfoEnricher.cs(22,51): error CS1525: Invalid expression term 'throw' [C:\projects\classic-webapi\src\SerilogWeb.Classic.WebApi\SerilogWeb.Classic.WebApi.csproj]
Classic\WebApi\Enrichers\BaseWebApiContextInfoEnricher.cs(22,51): error CS1002: ; expected [C:\projects\classic-webapi\src\SerilogWeb.Classic.WebApi\SerilogWeb.Classic.WebApi.csproj]
Attempting to build package from 'SerilogWeb.Classic.WebApi.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find 'C:\projects\classic-webapi\src\SerilogWeb.Classic.WebApi\bin\Release\SerilogWeb.Classic.WebApi.dll'. Make sure the project has been built.
```

This looks like a problem with using recent C# features in : 

https://github.com/serilog-web/classic-webapi/blob/d7042f54f7685ca4ada23c679ae8596cb116785b/src/SerilogWeb.Classic.WebApi/Classic/WebApi/Enrichers/BaseWebApiContextInfoEnricher.cs#L22

**Comment by tsimbalar** [comment]
see comments in https://github.com/serilog-web/classic-webapi/pull/4#issuecomment-347985714

**Comment by tsimbalar** [comment]
@nblumhardt I'm trying to fix this, but I'm a bit confused, as there is no `appveyor.yml` file in this repo ... is there somewhere special I should look in AppVeyor / some special privilege I need to log on there ? 

Thanks in advance

**Comment by nblumhardt** [comment]
Sorry about the confusion. You should be able to drop in a new appveyor.yml, perhaps by copying https://github.com/serilog-web/classic/blob/master/appveyor.yml - AppVeyor will pick this up automatically.

**Comment by tsimbalar** [comment]
oh, ok I thought there was some kind of secret zone in the AppVeyor Admin UI where I should do something ... 

I'll try what you said.

Thanks again !

**Comment by tsimbalar** [comment]
@nblumhardt sorry but I'm feeling quite useless here :-/  . I've added the appveyor.yml, but it still does not look like it's triggering a build ... I currently know nothing about AppVeyor and I can't see anything related to the serilog-web/* repos in the UI. Am I missing something obvious ? 

Should I see something like *serilog-web* in the AppVeyor login form ? 

![image](https://user-images.githubusercontent.com/160544/33483268-5c79b698-d69d-11e7-97f6-9fab89ada798.png)


Thanks again !

**Comment by nblumhardt** [comment]
Howdy! Sorry - have added you now, let me know if you don't get an invitation/see the account.

**Comment by tsimbalar** [comment]
I've updated the image used by AppVeyor so that it uses VS 2017 by default, and therefore supports C# 7+ features .... 

But still no luck. I find it strange that : 
- the build does not trigger itself on new commits
- the MSBuild version in the build log when triggered manually is v14 ( ~ VS 2015) 

see for instance https://ci.appveyor.com/project/serilog-web/classic-webapi/build/6#L351 :

`MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.` 

I'm not sure, but could it be possible that AppVeyor somehow fails to access the `appveyor.yml` file ? 

The account authorization seems to be about 1 year old ... could it have possibly expired ? 
![image](https://user-images.githubusercontent.com/160544/33553036-6594c5fe-d8f7-11e7-8a88-05063d1f77b0.png)

**Comment by tsimbalar** [comment]
Revoking and *re-granting* Github authorization seems to have unlocked the situation, and the compilation now properly works : 

```
Attempting to build package from 'SerilogWeb.Classic.WebApi.csproj'.
MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'
....
```

But now, publishing to NuGet seems to fail
```
Deploying using NuGet provider
Publishing SerilogWeb.Classic.WebApi.2.0.7.nupkg to https://www.nuget.org/api/v2/package...NuGet account requires protocol version 4.1.0 - using NuGet command line tool
Pushing SerilogWeb.Classic.WebApi.2.0.7.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Created https://www.nuget.org/api/v2/package/ 12568ms
Your package was pushed.
Pushing SerilogWeb.Classic.WebApi.2.0.7.symbols.nupkg to the symbol server (https://nuget.smbsrc.net/)...
  POST https://www.nuget.org/api/v2/package/create-verification-key/SerilogWeb.Classic.WebApi/2.0.7
  OK https://www.nuget.org/api/v2/package/create-verification-key/SerilogWeb.Classic.WebApi/2.0.7 726ms
  PUT https://nuget.smbsrc.net/api/v2/package/
  OK https://nuget.smbsrc.net/api/v2/package/ 3309ms
Your package was pushed.
Publishing SerilogWeb.Classic.WebApi.2.0.7.symbols.nupkg to https://nuget.smbsrc.net/api/v2/package...
Error publishing package. NuGet server returned 403: Forbidden
```

see https://ci.appveyor.com/project/serilog-web/classic-webapi/build/7#L306

... and yet the package seems to be on NuGet : https://www.nuget.org/packages/SerilogWeb.Classic.WebApi/2.0.7 ... I think the error is related to the *source symbols* package.

I am quite confused here, does anyone have an idea about what is going on ?

**Comment by tsimbalar** [comment]
I guess it was a temporary nuget.org quirk ... It works fine now !
